"""add_role_to_users_table

Revision ID: 99dbbd3990dd
Revises: 17d797292022
Create Date: 2025-11-22 11:17:22.727610

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99dbbd3990dd"
down_revision: str | None = "17d797292022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add role column with default value 'geral' for existing users
    op.add_column(
        "users", sa.Column("role", sa.String(length=20), nullable=False, server_default="geral")
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)

    # Migrate existing superusers to admin role
    op.execute("""
        UPDATE users
        SET role = 'admin'
        WHERE is_superuser = true
    """)

    # Migrate users with @realastrology.ai email to admin role
    op.execute("""
        UPDATE users
        SET role = 'admin'
        WHERE email LIKE '%@realastrology.ai'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_column("users", "role")
    # ### end Alembic commands ###
