"""add deleted_at to users table

Revision ID: 7b0e1bdd69f5
Revises: 26cd00243413
Create Date: 2025-11-16 02:23:03.170528

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b0e1bdd69f5'
down_revision: str | None = '26cd00243413'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'birth_charts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.drop_constraint(None, 'birth_charts', type_='foreignkey')
    op.create_table('chart_interpretations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interpretation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Type: 'planet', 'house', or 'aspect'"),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="e.g., 'Sun', '1', 'Sun-Trine-Moon'"),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='AI-generated interpretation text'),
    sa.Column('openai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="OpenAI model used (e.g., 'gpt-4o-mini')"),
    sa.Column('prompt_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Prompt version for tracking changes'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['birth_charts.id'], name='chart_interpretations_chart_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chart_interpretations_pkey')
    )
    op.create_index('ix_chart_interpretations_interpretation_type', 'chart_interpretations', ['interpretation_type'], unique=False)
    op.create_index('ix_chart_interpretations_id', 'chart_interpretations', ['id'], unique=False)
    op.create_index('ix_chart_interpretations_chart_id', 'chart_interpretations', ['chart_id'], unique=False)
    # ### end Alembic commands ###
