"""add pdf_generating and pdf_task_id fields to birth_charts

Revision ID: 17d797292022
Revises: ccc076a63ea8
Create Date: 2025-11-20 23:58:13.168871

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '17d797292022'
down_revision: str | None = 'ccc076a63ea8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add pdf_generating with server default for existing rows
    op.add_column('birth_charts', sa.Column('pdf_generating', sa.Boolean(), server_default=sa.false(), nullable=False))
    # Remove server default after column is created
    op.alter_column('birth_charts', 'pdf_generating', server_default=None)

    op.add_column('birth_charts', sa.Column('pdf_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_birth_charts_pdf_generating'), 'birth_charts', ['pdf_generating'], unique=False)
    op.create_index(op.f('ix_birth_charts_pdf_task_id'), 'birth_charts', ['pdf_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_birth_charts_pdf_task_id'), table_name='birth_charts')
    op.drop_index(op.f('ix_birth_charts_pdf_generating'), table_name='birth_charts')
    op.drop_column('birth_charts', 'pdf_task_id')
    op.drop_column('birth_charts', 'pdf_generating')
    # ### end Alembic commands ###
