"""add chart_interpretations table

Revision ID: 22f518a0295f
Revises: 14f966eaec6d
Create Date: 2025-11-15 13:35:52.460833

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22f518a0295f'
down_revision: str | None = '14f966eaec6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chart_id', sa.UUID(), nullable=False),
    sa.Column('interpretation_type', sa.String(length=20), nullable=False, comment="Type: 'planet', 'house', or 'aspect'"),
    sa.Column('subject', sa.String(length=100), nullable=False, comment="e.g., 'Sun', '1', 'Sun-Trine-Moon'"),
    sa.Column('content', sa.Text(), nullable=False, comment='AI-generated interpretation text'),
    sa.Column('openai_model', sa.String(length=50), nullable=False, comment="OpenAI model used (e.g., 'gpt-4o-mini')"),
    sa.Column('prompt_version', sa.String(length=20), nullable=False, comment='Prompt version for tracking changes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['birth_charts.id'], name='chart_interpretations_chart_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chart_interpretations_pkey')
    )
    op.create_index(op.f('ix_chart_interpretations_chart_id'), 'chart_interpretations', ['chart_id'], unique=False)
    op.create_index(op.f('ix_chart_interpretations_id'), 'chart_interpretations', ['id'], unique=False)
    op.create_index(op.f('ix_chart_interpretations_interpretation_type'), 'chart_interpretations', ['interpretation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chart_interpretations_interpretation_type'), table_name='chart_interpretations')
    op.drop_index(op.f('ix_chart_interpretations_id'), table_name='chart_interpretations')
    op.drop_index(op.f('ix_chart_interpretations_chart_id'), table_name='chart_interpretations')
    op.drop_table('chart_interpretations')
    # ### end Alembic commands ###
