"""add rag_sources to chart_interpretations

Revision ID: 61837bbf83a1
Revises: 303700b12232
Create Date: 2025-11-23 15:39:45.745380

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61837bbf83a1'
down_revision: str | None = '303700b12232'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_interpretations', sa.Column('rag_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='RAG document sources used for this interpretation'))
    op.create_index(op.f('ix_search_indices_index_name'), 'search_indices', ['index_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_indices_index_name'), table_name='search_indices')
    op.drop_column('chart_interpretations', 'rag_sources')
    # ### end Alembic commands ###
