"""Add async processing fields to BirthChart

Revision ID: b47c6865ccaf
Revises: 5d7ee6340019
Create Date: 2025-11-17 15:35:55.019625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b47c6865ccaf'
down_revision: Union[str, None] = '5d7ee6340019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_charts', sa.Column('status', sa.String(length=20), nullable=False, server_default='processing'))
    op.add_column('birth_charts', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('birth_charts', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('birth_charts', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.alter_column('birth_charts', 'chart_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_birth_charts_status'), 'birth_charts', ['status'], unique=False)
    op.create_index(op.f('ix_birth_charts_task_id'), 'birth_charts', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_birth_charts_task_id'), table_name='birth_charts')
    op.drop_index(op.f('ix_birth_charts_status'), table_name='birth_charts')
    op.alter_column('birth_charts', 'chart_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('birth_charts', 'task_id')
    op.drop_column('birth_charts', 'error_message')
    op.drop_column('birth_charts', 'progress')
    op.drop_column('birth_charts', 'status')
    # ### end Alembic commands ###
