"""add_user_consents_table

Revision ID: 26cd00243413
Revises: 2d5eb21ce250
Create Date: 2025-11-15 22:31:39.070624

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26cd00243413'
down_revision: str | None = '2d5eb21ce250'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False, comment='Type: terms, privacy, cookies, marketing'),
    sa.Column('version', sa.String(length=50), nullable=False, comment="Document version (e.g., '1.0', '2024-11-15')"),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IPv4 or IPv6 address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser user agent string'),
    sa.Column('consent_text', sa.Text(), nullable=True, comment='Snapshot of consent text at acceptance time'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_consent_type'), 'user_consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'birth_charts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.drop_constraint(None, 'birth_charts', type_='foreignkey')
    op.create_table('chart_interpretations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interpretation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Type: 'planet', 'house', or 'aspect'"),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="e.g., 'Sun', '1', 'Sun-Trine-Moon'"),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='AI-generated interpretation text'),
    sa.Column('openai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="OpenAI model used (e.g., 'gpt-4o-mini')"),
    sa.Column('prompt_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Prompt version for tracking changes'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['birth_charts.id'], name='chart_interpretations_chart_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chart_interpretations_pkey')
    )
    op.create_index('ix_chart_interpretations_interpretation_type', 'chart_interpretations', ['interpretation_type'], unique=False)
    op.create_index('ix_chart_interpretations_id', 'chart_interpretations', ['id'], unique=False)
    op.create_index('ix_chart_interpretations_chart_id', 'chart_interpretations', ['chart_id'], unique=False)
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_index(op.f('ix_user_consents_consent_type'), table_name='user_consents')
    op.drop_table('user_consents')
    # ### end Alembic commands ###
