"""add_password_reset_tokens_table

Revision ID: 2d5eb21ce250
Revises: 22f518a0295f
Create Date: 2025-11-15 22:16:16.275680

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d5eb21ce250'
down_revision: str | None = '22f518a0295f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index('ix_chart_interpretations_chart_id', table_name='chart_interpretations')
    op.drop_index('ix_chart_interpretations_id', table_name='chart_interpretations')
    op.drop_index('ix_chart_interpretations_interpretation_type', table_name='chart_interpretations')
    op.drop_table('chart_interpretations')
    op.create_foreign_key(None, 'birth_charts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.drop_constraint(None, 'birth_charts', type_='foreignkey')
    op.create_table('chart_interpretations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interpretation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Type: 'planet', 'house', or 'aspect'"),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="e.g., 'Sun', '1', 'Sun-Trine-Moon'"),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='AI-generated interpretation text'),
    sa.Column('openai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="OpenAI model used (e.g., 'gpt-4o-mini')"),
    sa.Column('prompt_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Prompt version for tracking changes'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['birth_charts.id'], name='chart_interpretations_chart_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chart_interpretations_pkey')
    )
    op.create_index('ix_chart_interpretations_interpretation_type', 'chart_interpretations', ['interpretation_type'], unique=False)
    op.create_index('ix_chart_interpretations_id', 'chart_interpretations', ['id'], unique=False)
    op.create_index('ix_chart_interpretations_chart_id', 'chart_interpretations', ['chart_id'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
