"""add pdf fields to birth_charts

Revision ID: b6028633621c
Revises: b47c6865ccaf
Create Date: 2025-11-20 10:17:57.560462

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6028633621c'
down_revision: str | None = 'b47c6865ccaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_charts', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    op.add_column('birth_charts', sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('birth_charts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('birth_charts', 'progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('birth_charts', 'progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('birth_charts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'processing'::character varying"),
               existing_nullable=False)
    op.drop_column('birth_charts', 'pdf_generated_at')
    op.drop_column('birth_charts', 'pdf_url')
    # ### end Alembic commands ###
