"""add language to chart_interpretations

Revision ID: 568668ec858b
Revises: 782ba409672f
Create Date: 2025-11-24 21:31:22.939967

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "568668ec858b"
down_revision: str | None = "782ba409672f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column(
        "chart_interpretations",
        sa.Column(
            "language",
            sa.String(length=10),
            nullable=True,
            server_default="pt-BR",
            comment="Language code (pt-BR or en-US)",
        ),
    )

    # Backfill existing rows with pt-BR (all existing interpretations are Portuguese)
    op.execute("UPDATE chart_interpretations SET language = 'pt-BR' WHERE language IS NULL")

    # Now make it non-nullable
    op.alter_column("chart_interpretations", "language", nullable=False)

    # Create index
    op.create_index(
        op.f("ix_chart_interpretations_language"),
        "chart_interpretations",
        ["language"],
        unique=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chart_interpretations_language"), table_name="chart_interpretations")
    op.drop_column("chart_interpretations", "language")
    # ### end Alembic commands ###
