"""add language to public_chart_interpretations

Revision ID: 9b5e1a052466
Revises: 568668ec858b
Create Date: 2025-11-24 21:35:05.149847

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b5e1a052466"
down_revision: str | None = "568668ec858b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Remove server_default from chart_interpretations.language (not needed after backfill)
    op.alter_column(
        "chart_interpretations",
        "language",
        existing_type=sa.VARCHAR(length=10),
        server_default=None,
        existing_comment="Language code (pt-BR or en-US)",
        existing_nullable=False,
    )

    # Add language column to public_chart_interpretations as nullable first
    op.add_column(
        "public_chart_interpretations",
        sa.Column(
            "language",
            sa.String(length=10),
            nullable=True,
            server_default="pt-BR",
            comment="Language code (pt-BR or en-US)",
        ),
    )

    # Backfill existing rows with pt-BR
    op.execute("UPDATE public_chart_interpretations SET language = 'pt-BR' WHERE language IS NULL")

    # Make it non-nullable
    op.alter_column("public_chart_interpretations", "language", nullable=False)

    # Create index
    op.create_index(
        op.f("ix_public_chart_interpretations_language"),
        "public_chart_interpretations",
        ["language"],
        unique=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_chart_interpretations_language"), table_name="public_chart_interpretations"
    )
    op.drop_column("public_chart_interpretations", "language")
    op.alter_column(
        "chart_interpretations",
        "language",
        existing_type=sa.VARCHAR(length=10),
        server_default=sa.text("'pt-BR'::character varying"),
        existing_comment="Language code (pt-BR or en-US)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
