"""Add password_changed_at field to users table

Revision ID: b0ef95f73d85
Revises: b6028633621c
Create Date: 2025-11-20 17:06:50.172287

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0ef95f73d85"
down_revision: str | None = "b6028633621c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_changed_at")
    # ### end Alembic commands ###
