"""add_is_featured_to_blog_posts

Revision ID: 55361a122379
Revises: 7a6c838f8b19
Create Date: 2025-11-25 13:35:31.030747

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55361a122379"
down_revision: str | None = "7a6c838f8b19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_posts",
        sa.Column("is_featured", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f("ix_blog_posts_is_featured"), "blog_posts", ["is_featured"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blog_posts_is_featured"), table_name="blog_posts")
    op.drop_column("blog_posts", "is_featured")
    # ### end Alembic commands ###
