"""add interpretation_cache table

Revision ID: 44bae117595b
Revises: 17d797292022
Create Date: 2025-11-22 10:40:00.767253

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44bae117595b'
down_revision: str | None = '17d797292022'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpretation_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('interpretation_type', sa.String(length=20), nullable=False, comment="Type: 'planet', 'house', or 'aspect'"),
    sa.Column('subject', sa.String(length=100), nullable=False, comment="e.g., 'Sun', '1', 'Sun-Trine-Moon'"),
    sa.Column('content', sa.Text(), nullable=False, comment='AI-generated interpretation text'),
    sa.Column('parameters_json', sa.Text(), nullable=False, comment='JSON of parameters used to generate this interpretation'),
    sa.Column('openai_model', sa.String(length=50), nullable=False, comment="OpenAI model used (e.g., 'gpt-4o-mini')"),
    sa.Column('prompt_version', sa.String(length=20), nullable=False, comment='Prompt version for tracking changes'),
    sa.Column('hit_count', sa.Integer(), nullable=False, comment='Number of times this cache entry was used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last time this cache entry was accessed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interpretation_cache_cache_key'), 'interpretation_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_interpretation_cache_id'), 'interpretation_cache', ['id'], unique=False)
    op.create_index(op.f('ix_interpretation_cache_interpretation_type'), 'interpretation_cache', ['interpretation_type'], unique=False)
    op.create_index(op.f('ix_interpretation_cache_last_accessed_at'), 'interpretation_cache', ['last_accessed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interpretation_cache_last_accessed_at'), table_name='interpretation_cache')
    op.drop_index(op.f('ix_interpretation_cache_interpretation_type'), table_name='interpretation_cache')
    op.drop_index(op.f('ix_interpretation_cache_id'), table_name='interpretation_cache')
    op.drop_index(op.f('ix_interpretation_cache_cache_key'), table_name='interpretation_cache')
    op.drop_table('interpretation_cache')
    # ### end Alembic commands ###
