"""add_public_charts_table

Revision ID: a353cbccb342
Revises: time_format_183000
Create Date: 2025-11-23 01:04:14.595978

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a353cbccb342'
down_revision: str | None = 'time_format_183000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('birth_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('birth_timezone', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('house_system', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('short_bio', sa.Text(), nullable=True),
    sa.Column('highlights', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_charts_category'), 'public_charts', ['category'], unique=False)
    op.create_index(op.f('ix_public_charts_created_at'), 'public_charts', ['created_at'], unique=False)
    op.create_index(op.f('ix_public_charts_featured'), 'public_charts', ['featured'], unique=False)
    op.create_index(op.f('ix_public_charts_id'), 'public_charts', ['id'], unique=False)
    op.create_index(op.f('ix_public_charts_is_published'), 'public_charts', ['is_published'], unique=False)
    op.create_index(op.f('ix_public_charts_slug'), 'public_charts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_charts_slug'), table_name='public_charts')
    op.drop_index(op.f('ix_public_charts_is_published'), table_name='public_charts')
    op.drop_index(op.f('ix_public_charts_id'), table_name='public_charts')
    op.drop_index(op.f('ix_public_charts_featured'), table_name='public_charts')
    op.drop_index(op.f('ix_public_charts_created_at'), table_name='public_charts')
    op.drop_index(op.f('ix_public_charts_category'), table_name='public_charts')
    op.drop_table('public_charts')
    # ### end Alembic commands ###
