"""add user profile fields

Revision ID: 5d7ee6340019
Revises: 7b0e1bdd69f5
Create Date: 2025-11-16 17:43:02.682977

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d7ee6340019'
down_revision: str | None = '7b0e1bdd69f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chart_interpretations_chart_id', table_name='chart_interpretations')
    op.drop_index('ix_chart_interpretations_id', table_name='chart_interpretations')
    op.drop_index('ix_chart_interpretations_interpretation_type', table_name='chart_interpretations')
    op.drop_table('chart_interpretations')

    # Add new columns (nullable first to handle existing rows)
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_public', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('allow_email_notifications', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('analytics_consent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE users SET profile_public = false WHERE profile_public IS NULL")
    op.execute(
        "UPDATE users SET allow_email_notifications = true WHERE allow_email_notifications IS NULL"
    )
    op.execute("UPDATE users SET analytics_consent = true WHERE analytics_consent IS NULL")

    # Make columns NOT NULL
    op.alter_column('users', 'profile_public', nullable=False, server_default=sa.text('false'))
    op.alter_column(
        'users', 'allow_email_notifications', nullable=False, server_default=sa.text('true')
    )
    op.alter_column('users', 'analytics_consent', nullable=False, server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'analytics_consent')
    op.drop_column('users', 'allow_email_notifications')
    op.drop_column('users', 'profile_public')
    op.drop_column('users', 'bio')
    op.create_table('chart_interpretations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interpretation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Type: 'planet', 'house', or 'aspect'"),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="e.g., 'Sun', '1', 'Sun-Trine-Moon'"),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='AI-generated interpretation text'),
    sa.Column('openai_model', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="OpenAI model used (e.g., 'gpt-4o-mini')"),
    sa.Column('prompt_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Prompt version for tracking changes'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['birth_charts.id'], name='chart_interpretations_chart_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chart_interpretations_pkey')
    )
    op.create_index('ix_chart_interpretations_interpretation_type', 'chart_interpretations', ['interpretation_type'], unique=False)
    op.create_index('ix_chart_interpretations_id', 'chart_interpretations', ['id'], unique=False)
    op.create_index('ix_chart_interpretations_chart_id', 'chart_interpretations', ['chart_id'], unique=False)
    # ### end Alembic commands ###
