"""add user profile expansion fields

Revision ID: 2f5d48c07f14
Revises: 17d797292022
Create Date: 2025-11-22 11:25:43.365167

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f5d48c07f14"
down_revision: str | None = "17d797292022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add user_type with server default for existing rows
    op.add_column(
        "users",
        sa.Column("user_type", sa.String(length=50), nullable=False, server_default="curious"),
    )
    op.add_column("users", sa.Column("website", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("instagram", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("twitter", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("location", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("professional_since", sa.Integer(), nullable=True))
    op.add_column(
        "users",
        sa.Column("specializations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "specializations")
    op.drop_column("users", "professional_since")
    op.drop_column("users", "location")
    op.drop_column("users", "twitter")
    op.drop_column("users", "instagram")
    op.drop_column("users", "website")
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###
